[env:ttgo-t5-213]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
  ZinggJM/GxEPD2 @ ^1.6.0
  bblanchon/ArduinoJson @ ^7.0.0
  arduino-libraries/ArduinoHttpClient @ ^0.6.0

build_flags =
  -DCORE_DEBUG_LEVEL=0
  ; Disable Bluetooth stack to free ~25 mA and ~60 KB RAM
  -DCONFIG_BT_ENABLED=0
  -DCONFIG_BLUEDROID_ENABLED=0
