[env:ttgo-t5-213]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
  ZinggJM/GxEPD2 @ ^1.6.0
  bblanchon/ArduinoJson @ ^7.0.0
  arduino-libraries/ArduinoHttpClient @ ^0.6.0
  knolleary/PubSubClient @ ^2.8

build_flags =
  -DCORE_DEBUG_LEVEL=0
  -Wl,--gc-sections
